language: 8
sudo: required
compiler:
- gcc
- clang
os:
- linux
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
cache:
  directories:
    - node_modules
install:
# - ./utils/travis/install.sh
- npm install
script:
- npm run compile &> compile.log || cat compile.log
- npm run 
- npm run devchain > ganache.log &
- sleep 20
- npm run test
# - npm run oyente
- npm run lint
after_script:
- cat ganache.log
